# Generated by Django 2.0.3 on 2018-05-09 19:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Area_Classe_Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('desvios', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Classe_Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco_atendimento', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('nivel_especialidade', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)])),
                ('nivel_tecnologia', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)])),
                ('media_conforto', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)])),
                ('velocidade_atendimento', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('salario', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('expertise', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('atendimento', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('pontualidade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('custo_de_aquisicao', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('custo_mensal', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tecnologia', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('conforto', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('capacidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preco_do_tratamento', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Multiplicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventoNome', models.CharField(max_length=50)),
                ('classeNome', models.CharField(max_length=50)),
                ('valor', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroRodada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duracao', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('evento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jogo.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=20)),
                ('caixa', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.AddField(
            model_name='area_classe_social',
            name='classe_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.Classe_Social'),
        ),
    ]
