# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 17:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('multiplicador_classeA', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('multiplicador_classeB', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('multiplicador_classeC', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('multiplicador_classeD', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('multiplicador_classeE', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name_plural': 'eventos',
                'verbose_name': 'evento',
            },
        ),
    ]
