# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0002_time'),
        ('jogo', '0002_evento'),
    ]

    operations = [
    ]
